//TIPS
export const FLIP_TIP_CARD = 'FLIP_TIP_CARD';
export const LOADING_TIPS = 'LOADING_TIPS';
export const RECEIVED_TIPS = 'RECEIVED_TIPS';
export const OPEN_TIPS_MODAL = 'OPEN_TIPS_MODAL';
export const CLOSE_TIPS_MODAL = 'CLOSE_TIPS_MODAL';
export const NEXT_TIP = 'NEXT_TIP';
export const PREV_TIP = 'PREV_TIP';

//MISC
export const MENU_CLICK = 'MENU_CLICK';
export const RESET = 'RESET';
export const UPDATE_THRESHOLD = 'UPDATE_THRESHOLD';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const RETRIEVE_NOTIFICATIONS = 'RETRIEVE_NOTIFICATIONS';
export const OPEN_NOTIFICATIONS = 'OPEN_NOTIFICATIONS';
export const CLOSE_NOTIFICATIONS = 'CLOSE_NOTIFICATIONS';
export const RETRIEVE_SOCKET_LOCATION = 'RETRIEVE_SOCKET_LOCATION';

//SENSORS
export const REMOVE_SENSOR = 'REMOVE_SENSOR';
export const VIEW_MODE = 'VIEW_MODE';
export const UPDATE_SENSOR = 'UPDATE_SENSOR';
export const FLIP_SENSOR_CARD = 'FLIP_SENSOR_CARD';
export const LOAD_SENSOR = 'LOAD_SENSOR';
export const SAVE_SENSOR = 'SAVE_SENSOR';
export const RECEIVED_LIVE_DATA = 'RECEIVED_LIVE_DATA';
export const LOADING_HISTORICAL_DATA = 'LOADING_HISTORICAL_DATA';
export const RECEIVED_HISTORICAL_DATA = 'RECEIVED_HISTORICAL_DATA';
export const RESET_LIVE_DATA = 'RESET_LIVE_DATA';
export const RESET_HISTORICAL_DATA = 'RESET_HISTORICAL_DATA';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const FILTER_SENSORS = 'FILTER_SENSORS';
export const UPDATE_START_DATE = 'UPDATE_START_DATE';
export const UPDATE_END_DATE = 'UPDATE_END_DATE';
export const RESET_HISTORICAL_DATES = 'RESET_HISTORICAL_DATES';
export const UPDATE_HOURLY_START_DATE = 'UPDATE_HOURLY_START_DATE';
export const UPDATE_HOURLY_END_DATE = 'UPDATE_HOURLY_END_DATE';
export const UPDATE_HISTORICAL_LOCAITON = 'UPDATE_HISTORICAL_LOCAITON';
export const UPDATE_HISTORICAL_RESOLUTION = 'UPDATE_HISTORICAL_RESOLUTION';
