//TIPS
export const FLIP_TIP_CARD = 'FLIP_TIP_CARD';

//MISC
export const MENU_CLICK = 'MENU_CLICK';
export const RESET = 'RESET';
export const UPDATE_THRESHOLD = 'UPDATE_THRESHOLD';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';

//SENSORS
export const REMOVE_SENSOR = 'REMOVE_SENSOR';
export const VIEW_MODE = 'VIEW_MODE';
export const UPDATE_SENSOR = 'UPDATE_SENSOR';
export const FLIP_SENSOR_CARD = 'FLIP_SENSOR_CARD';
export const LOAD_SENSOR = 'LOAD_SENSOR';
export const SAVE_SENSOR = 'SAVE_SENSOR';
export const RECEIVED_LIVE_DATA = 'RECEIVED_LIVE_DATA';
export const LOADING_HISTORICAL_DATA = 'LOADING_HISTORICAL_DATA';
export const RECEIVED_HISTORICAL_DATA = 'RECEIVED_HISTORICAL_DATA';
export const RESET_LIVE_DATA = 'RESET_LIVE_DATA';
export const RESET_HISTORICAL_DATA = 'RESET_HISTORICAL_DATA';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const FILTER_SENSORS = 'FILTER_SENSORS';
